// Initial seed data for Survey 593 React Platform

export const INITIAL_USERS = [
  // Providers (Empresas)
  {
    id: 'prov_1',
    name: 'Textil Andina S.A.',
    email: 'admin@textilandina.ec',
    password: 'demo123',
    role: 'provider',
    company: 'Textil Andina',
    industry: 'Moda y Textiles',
    ruc: '1793204829001',
    verified: true,
    balance: 5000,
    avatarColor: '#0D9488',
    createdAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 'prov_2',
    name: 'Campaña Progreso 2026',
    email: 'director@progreso2026.ec',
    password: 'demo123',
    role: 'provider',
    company: 'Partido Progreso',
    industry: 'Política',
    ruc: '1791234567001',
    verified: true,
    balance: 12000,
    avatarColor: '#6366F1',
    createdAt: '2026-06-20T14:30:00Z',
  },
  {
    id: 'prov_3',
    name: 'ClínicaVida',
    email: 'gerencia@clinicavida.ec',
    password: 'demo123',
    role: 'provider',
    company: 'ClínicaVida',
    industry: 'Salud',
    ruc: '1792345678001',
    verified: true,
    balance: 3500,
    avatarColor: '#EC4899',
    createdAt: '2026-07-01T09:00:00Z',
  },

  // Doers (Encuestados)
  {
    id: 'doer_1',
    name: 'María García López',
    email: 'maria@email.com',
    password: 'demo123',
    role: 'doer',
    cedula: '1724589302',
    age: 28,
    city: 'Quito',
    gender: 'F',
    verified: true,
    balance: 47.5,
    surveysCompleted: 12,
    streak: 5,
    avatarColor: '#F59E0B',
    createdAt: '2026-07-05T08:00:00Z',
  },
  {
    id: 'doer_2',
    name: 'Carlos Mendoza',
    email: 'carlos@email.com',
    password: 'demo123',
    role: 'doer',
    cedula: '1710034065',
    age: 35,
    city: 'Guayaquil',
    gender: 'M',
    verified: true,
    balance: 32.0,
    surveysCompleted: 8,
    streak: 3,
    avatarColor: '#EF4444',
    createdAt: '2026-07-06T10:00:00Z',
  },
  {
    id: 'doer_3',
    name: 'Ana Lucía Herrera',
    email: 'ana@email.com',
    password: 'demo123',
    role: 'doer',
    age: 22,
    city: 'Cuenca',
    gender: 'F',
    verified: true,
    balance: 15.75,
    surveysCompleted: 5,
    streak: 1,
    avatarColor: '#8B5CF6',
    createdAt: '2026-07-10T12:00:00Z',
  },
  {
    id: 'doer_4',
    name: 'Roberto Paz Torres',
    email: 'roberto@email.com',
    password: 'demo123',
    role: 'doer',
    age: 42,
    city: 'Quito',
    gender: 'M',
    verified: false,
    balance: 8.25,
    surveysCompleted: 3,
    streak: 0,
    avatarColor: '#10B981',
    createdAt: '2026-07-12T16:00:00Z',
  },

  // Admin
  {
    id: 'admin_1',
    name: 'Admin Kolab',
    email: 'admin@kolab.ec',
    password: 'admin123',
    role: 'admin',
    verified: true,
    avatarColor: '#3B82F6',
    createdAt: '2026-06-01T00:00:00Z',
  },
];

export const INITIAL_SURVEYS = [
  {
    id: 'surv_1',
    providerId: 'prov_1',
    title: 'Preferencias de Moda Urbana 2026',
    description: 'Ayúdanos a entender las tendencias de moda que más te gustan en ropa casual y sostenible.',
    category: 'Moda',
    status: 'active',
    rewardPerResponse: 3.5,
    budget: 350,
    spent: 42,
    targetResponses: 100,
    actualResponses: 12,
    estimatedTime: 5,
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'surv_2',
    providerId: 'prov_2',
    title: 'Percepción del Servicio Público en tu Ciudad',
    description: 'Queremos conocer tu opinión sobre el transporte, seguridad y salud pública en tu ciudad.',
    category: 'Gobierno',
    status: 'active',
    rewardPerResponse: 2.5,
    budget: 500,
    spent: 20,
    targetResponses: 200,
    actualResponses: 8,
    estimatedTime: 7,
    createdAt: '2026-07-22T14:00:00Z',
  },
  {
    id: 'surv_3',
    providerId: 'prov_3',
    title: 'Experiencia del Paciente - ClínicaVida',
    description: 'Tu opinión médica nos ayuda a mejorar la atención de consultas externas y emergencias.',
    category: 'Salud',
    status: 'active',
    rewardPerResponse: 4.0,
    budget: 200,
    spent: 32,
    targetResponses: 50,
    actualResponses: 8,
    estimatedTime: 4,
    createdAt: '2026-07-25T09:00:00Z',
  },
];

export const INITIAL_QUESTIONS = [
  // Survey 1 (Moda)
  {
    id: 'q1_1',
    surveyId: 'surv_1',
    order: 1,
    type: 'multiple',
    text: '¿Qué estilo de ropa prefieres para el día a día?',
    required: true,
    options: ['Casual urbano', 'Deportivo', 'Formal-casual', 'Bohemio', 'Minimalista'],
  },
  {
    id: 'q1_2',
    surveyId: 'surv_1',
    order: 2,
    type: 'likert',
    text: '¿Qué tan importante es para ti que la ropa sea producida de forma sostenible?',
    required: true,
    scale: 5,
    labels: ['Nada importante', 'Poco', 'Neutral', 'Importante', 'Muy importante'],
  },
  {
    id: 'q1_3',
    surveyId: 'surv_1',
    order: 3,
    type: 'multiple',
    text: '¿Cuánto gastas mensualmente en ropa?',
    required: true,
    options: ['Menos de $30', '$30 - $60', '$60 - $100', '$100 - $200', 'Más de $200'],
  },
  {
    id: 'q1_4',
    surveyId: 'surv_1',
    order: 4,
    type: 'yesno',
    text: '¿Comprarías ropa de una marca nueva ecuatoriana con buenas reseñas?',
    required: true,
  },
  {
    id: 'q1_5',
    surveyId: 'surv_1',
    order: 5,
    type: 'text',
    text: '¿Qué marca de ropa local recomiendas y por qué?',
    required: false,
  },

  // Survey 2 (Gobierno)
  {
    id: 'q2_1',
    surveyId: 'surv_2',
    order: 1,
    type: 'likert',
    text: '¿Cómo calificas el servicio de transporte público?',
    required: true,
    scale: 5,
    labels: ['Muy malo', 'Malo', 'Regular', 'Bueno', 'Excelente'],
  },
  {
    id: 'q2_2',
    surveyId: 'surv_2',
    order: 2,
    type: 'multiple',
    text: '¿Cuál consideras el problema más urgente de tu ciudad?',
    required: true,
    options: ['Inseguridad', 'Transporte', 'Salud pública', 'Educación', 'Empleo'],
  },
];

export const INITIAL_RESPONSES = [
  {
    id: 'resp_1',
    surveyId: 'surv_1',
    userId: 'doer_1',
    answers: {
      q1_1: 'Casual urbano',
      q1_2: 4,
      q1_3: '$60 - $100',
      q1_4: 'Sí',
      q1_5: 'Pinto, excelente calidad.',
    },
    verified: true,
    completedAt: '2026-08-10T14:30:00Z',
  },
  {
    id: 'resp_2',
    surveyId: 'surv_1',
    userId: 'doer_2',
    answers: {
      q1_1: 'Deportivo',
      q1_2: 3,
      q1_3: '$30 - $60',
      q1_4: 'Sí',
      q1_5: '',
    },
    verified: true,
    completedAt: '2026-08-11T16:00:00Z',
  },
  {
    id: 'resp_3',
    surveyId: 'surv_1',
    userId: 'doer_3',
    answers: {
      q1_1: 'Minimalista',
      q1_2: 5,
      q1_3: '$100 - $200',
      q1_4: 'Sí',
      q1_5: 'Marcas independientes de diseño.',
    },
    verified: true,
    completedAt: '2026-08-12T10:15:00Z',
  },
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'txn_1',
    userId: 'doer_1',
    type: 'income',
    amount: 3.5,
    description: 'Encuesta: Moda Urbana',
    status: 'completed',
    createdAt: '2026-08-10T14:30:00Z',
  },
  {
    id: 'txn_2',
    userId: 'doer_1',
    type: 'income',
    amount: 2.5,
    description: 'Encuesta: Servicio Público',
    status: 'completed',
    createdAt: '2026-08-11T12:00:00Z',
  },
  {
    id: 'txn_3',
    userId: 'doer_1',
    type: 'withdrawal',
    amount: -25.0,
    description: 'Retiro a Banco Pichincha',
    status: 'completed',
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const INITIAL_CUSTOM_DASHBOARDS = [
  {
    id: 'dash_1',
    providerId: 'prov_1',
    title: 'Tablero Estratégico de Moda & Consumo',
    description: 'Dashboard interactivo con gráficos de Pastel, Radar multidimensional y métricas financieras de gasto.',
    createdAt: '2026-08-15T10:00:00Z',
    widgets: [
      {
        id: 'w_1',
        type: 'kpi',
        title: 'Muestra Total Recolectada',
        surveyId: 'surv_1',
        colSpan: 1,
        config: { metric: 'total_responses', label: 'Encuestados Verificados (Quito/Gye)' },
      },
      {
        id: 'w_2',
        type: 'kpi',
        title: 'Índice de Sostenibilidad',
        surveyId: 'surv_1',
        questionId: 'q1_2',
        colSpan: 1,
        config: { metric: 'avg_likert', label: 'Promedio sobre 5.0 ★' },
      },
      {
        id: 'w_3',
        type: 'pie',
        title: 'Preferencia de Estilo de Ropa (Pastel)',
        surveyId: 'surv_1',
        questionId: 'q1_1',
        colSpan: 1,
        config: {},
      },
      {
        id: 'w_4',
        type: 'radar',
        title: 'Perfil de Consumo & Sostenibilidad (Radar)',
        surveyId: 'surv_1',
        questionId: 'q1_2',
        colSpan: 1,
        config: { label: 'Sensibilidad Sostenible' },
      },
      {
        id: 'w_5',
        type: 'bar',
        title: 'Distribución de Gasto Mensual ($)',
        surveyId: 'surv_1',
        questionId: 'q1_3',
        colSpan: 2,
        config: {},
      },
    ],
  },
];
